name: Backend CD

on:
  workflow_run:
    workflows: ["Backend CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # Ensure this is correct

      - name: Register New Task Definition Revision
        id: register-task
        run: |
          # Get current task definition
          NEW_TASK_DEF=$(aws ecs describe-task-definition --task-definition MyAskPdfBackendTask)

          # Strip unnecessary fields for new registration
          echo "$NEW_TASK_DEF" | jq '.taskDefinition | del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)' > new-task-def.json

          # Update with latest Docker image from DockerHub
          jq --arg IMAGE "docker.io/${{ secrets.DOCKERHUB_USERNAME }}/ask-pdf-backend:latest" '.containerDefinitions[0].image = $IMAGE' new-task-def.json > updated-task-def.json

          # Register new task definition and get its revision number
          NEW_REVISION=$(aws ecs register-task-definition --cli-input-json file://updated-task-def.json | jq -r '.taskDefinition.revision')
          echo "NEW_REVISION=$NEW_REVISION" >> $GITHUB_ENV
          echo "New task definition revision: $NEW_REVISION"

      - name: Deploy New Task to ECS
        run: |
          aws ecs update-service --cluster MyAskPdfBackendCluster --service ask-pdf-backend-service --task-definition MyAskPdfBackendTask:$NEW_REVISION --force-new-deployment
