name: Backend CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build backend Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ask-pdf-backend:latest .

      - name: Push backend image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ask-pdf-backend:latest

      - name: Cleanup old Docker images (Optional)
        run: docker system prune -af
